services:
  - type: web
    name: jalrakshak-backend
    runtime: node
    rootDir: jalrakshak-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false

  - type: web
    name: jalrakshak-user-dashboard
    runtime: node
    rootDir: jalrakshak-user
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
